### ISSUE TITLE
STONK-9: Frontend > Setup TypeScript

### ISSUE THREAD

**Issue by JackyTea** [JackyTea/Mock-Stocks-Collaborative#10]
## Description

We want to migrate over from vanilla JS to TypeScript for type safety and better scalability in terms of our codebase. 

## Acceptance Criteria

- install `typescript`
- make a `build` command for the app `e.g. tsc-node index.ts`
- configure a `tsconfig.json` file

## Checklist

- [x] I have verified that this issue is relevant to the current project scope
- [x] I have added the appropriate label to this issue
- [x] I have linked this issue to the project
- [x] I have followed the issue title pattern of `STONK-NUMBER: Domain > Issue Title`

**Comment by one2code** [comment]
I'll work on this. Does the TS migration include frontend only, or do you want to do a backend migration as well?
